name: first workflow1

on:
  push:
    branches:
      - main

jobs:
  githubactions-tcu-01:
    runs-on: ubuntu-latest
    steps:
      - name: create-tcu
        run: echo "vou pro tcu" > file.txt
      - name: read-tcu
        run: cat file.txt