name: first workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Enter the docker image name you wanna for the job tcu-01
        type: string
        required: true

jobs:
  githubactions-tcu-01:
    runs-on: ${{ inputs.environment }}
    steps:
      - name: create-tcu
        run: echo "vou pro tcu" > file.txt
      - name: read-tcu
        run: cat file.txt

  githubactions-tcu-02:
    runs-on: ubuntu-latest
    steps:
      - name: create-tcu
        run: echo "vou pro tcu" > ${{ github.workspace }}/file.txt
      - uses: actions/upload-artifact@v4 #vai apos o arquivo ter sido criado, o que ele faz Ã© fazer o upload
        with: 
          name: dumps
          path: ${{ github.workspace }}/file.txt
      - name: checking workspace
        run: ls -lha  ${{ github.workspace }}

  githubactions-tcu-03:
    runs-on: ubuntu-latest
    needs: githubactions-tcu-02
    steps:
      - uses: actions/download-artifact@v4 #faz o download do arquivo, obviamente tem que ir antes de ler o arquivo na pasta
        with: 
          name: dumps
          path: imports
      - name: Ver o conteudo do diretorio
        run: ls -lha && ls ./imports/
      - name: Imprimir conteudo do arquivo

        run: cat ./imports/file.txt        

