name: first workflow

on:
  push:
    branches:
      - main

jobs:
  githubactions-tcu-01:
    runs-on: ubuntu-latest
    steps:
      - name: create-tcu
        run: echo "vou pro tcu" > file.txt
      - name: read-tcu
        run: cat file.txt
  githubactions-tcu-02:
    runs-on: ubuntu-latest
    steps:
      - name: checking directory
        run: ls -lha
      - name: create-tcu
        run: echo "vou pro tcu" > ${{ github.workspace }}/file.txt
      - name: checking directory again
        run: ls -lha       
      - uses: actions/upload-artifact@v4
        with: 
          name: dumps
          path: ${{ github.workspace }}/file.txt
      - name: checking workspace
        run: ls -lha  ${{ github.workspace }}                