name: trigger when a pull request is created, edited or deleted in dev branch

on:
  pull_request:
    types: [opened, edited, deleted, reopened]
    branches:
      - dev

job:
  trigger-pull-request:
  runs-on: ubuntu-latest
    - name: triggered
      run: echo "new pull request was created on dev."

